<?php
declare(strict_types=1);
require __DIR__ . '/auth-lib.php';
canada_require_login();
$profileId = canada_profile();
$profile = CANADA_PROFILES[$profileId];
?>
<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#143b2b"><meta name="description" content="Canada 2027 – zentrale Übersicht aller Reiseentscheidungen"><meta name="robots" content="noindex,nofollow"><title>Abstimmungen · Canada 2027</title><link rel="stylesheet" href="styles.css?v=20260907-1"></head>
<body class="dashboard-page"><header class="topbar"><a class="brand" href="index.php"><span class="brand-mark">🍁</span><span><strong>Canada 2027</strong><small>17. September – 2. Oktober</small></span></a><nav class="desktop-nav"><a href="index.php">Reise</a><a class="active" href="abstimmungen.php">Abstimmen</a><a href="index.php#checklists">Checklisten</a></nav><a class="profile-chip" href="login.php?switch=1&amp;next=%2Fabstimmungen.php" aria-label="Profil wechseln"><i class="avatar <?= htmlspecialchars($profile['avatar'], ENT_QUOTES) ?>"></i><span><?= htmlspecialchars($profile['name']) ?></span></a></header>
<main class="vote-dashboard"><section class="dashboard-hero"><div><p class="eyebrow">Eure Reiseentscheidungen</p><h1>Was möchtest du als Nächstes entscheiden?</h1><p>Hier siehst du nur den Stand. Bewerten, auswählen und kommentieren kannst du auf den bereits vorhandenen Detailseiten.</p></div><div class="dashboard-progress" aria-live="polite"><span id="dashboard-percent">–</span><small>deiner Entscheidungen erledigt</small><div><i id="dashboard-progress-bar"></i></div></div></section>
<section class="dashboard-personal" aria-labelledby="dashboard-personal-title"><div class="dashboard-user"><i class="avatar <?= htmlspecialchars($profile['avatar'], ENT_QUOTES) ?>"></i><div><p class="eyebrow">Persönlicher Stand</p><h2 id="dashboard-personal-title"><?= htmlspecialchars($profile['name']) ?>, hier geht es für dich weiter</h2><p id="dashboard-personal-copy">Die Abstimmungen werden geladen …</p></div></div><div class="dashboard-roster" id="dashboard-roster" aria-label="Stand der vier Reisenden"></div></section>
<nav class="dashboard-filters" aria-label="Abstimmungen filtern"><button class="active" type="button" data-dashboard-filter="mine">Meine offenen</button><button type="button" data-dashboard-filter="open">Alle offenen</button><button type="button" data-dashboard-filter="done">Entschieden</button><button type="button" data-dashboard-filter="booked">Gebucht</button></nav>
<div id="dashboard-status" class="dashboard-loading">Aktueller Stand wird zusammengetragen …</div><section id="dashboard-list" class="dashboard-list" aria-live="polite"></section></main>
<nav class="mobile-nav dashboard-mobile-nav" aria-label="Mobile Navigation"><a href="index.php"><span>⌁</span>Reise</a><a class="active" href="abstimmungen.php"><span>★</span>Abstimmen</a><a href="index.php#checklists"><span>✓</span>Listen</a><a href="index.php#travellers"><span>♙</span>Wir vier</a></nav><script src="dashboard.js?v=20260906-11"></script></body></html>
