const people = ["lars", "andrea", "christina", "manfred"];
const names = { lars: "Lars", andrea: "Andrea", christina: "Christina", manfred: "Manfred" };
const avatars = { lars: "avatar-lars", andrea: "avatar-andrea", christina: "avatar-christina", manfred: "avatar-manfred" };
let current = "", csrf = "", filter = "mine", decisions = [], fixedDecisions = {};

const esc = value => String(value ?? "").replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character]));
async function json(url) { const response = await fetch(`${url}${url.includes("?") ? "&" : "?"}t=${Date.now()}`, { cache: "no-store" }); if (!response.ok) throw new Error("Ein Teil der Abstimmungen konnte nicht geladen werden."); return response.json(); }
async function saveDecision(body) { const response = await fetch("decision-status.php", { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": csrf }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Entscheidung konnte nicht gespeichert werden."); fixedDecisions = data.decisions || {}; applyStates(); render(); }

const ratings = record => people.filter(person => Number(record?.[person] || 0) > 0);
const choices = record => people.filter(person => Boolean(record?.[person]));
const both = (...groups) => people.filter(person => groups.every(group => group.includes(person)));
const variants = (data, ids) => people.filter(person => ids.every(id => Number(data?.variants?.[id]?.ratings?.[person] || 0) > 0));
const ideaRatings = rows => people.filter(person => rows.every(row => Number(row?.ratings?.[person] || 0) > 0));
function average(record) { const values = Object.values(record || {}).map(Number).filter(value => value > 0); return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0; }
function ratingFavorite(options, take = 1) { const ranked = options.map(option => ({ ...option, score: average(option.ratings) })).filter(option => option.score > 0).sort((a, b) => b.score - a.score); if (!ranked.length) return "Noch kein Favorit"; if (take > 1) return ranked.slice(0, take).map(option => option.label).join(" + "); const best = ranked[0].score, leaders = ranked.filter(option => Math.abs(option.score - best) < .001); return leaders.length > 1 ? `Gleichstand: ${leaders.map(option => option.label).join(" / ")}` : leaders[0].label; }
function choiceFavorite(record, labels) { const counts = {}; Object.values(record || {}).forEach(choice => { if (choice) counts[choice] = (counts[choice] || 0) + 1; }); const ranked = Object.entries(counts).sort((a, b) => b[1] - a[1]); if (!ranked.length) return "Noch kein Favorit"; const best = ranked[0][1], leaders = ranked.filter(([, count]) => count === best).map(([id]) => labels[id] || id); return leaders.length > 1 ? `Gleichstand: ${leaders.join(" / ")}` : leaders[0]; }
function makeItem(data) { return { ...data, complete: data.donePeople.length === 4, mineDone: data.donePeople.includes(current) }; }
function applyStates() { decisions = decisions.map(decision => { if (decision.booked) return { ...decision, state: "booked", fixed: null }; const fixed = fixedDecisions[decision.id] || null; return { ...decision, fixed, state: fixed ? "fixed" : decision.complete ? "ready" : "open" }; }); }

async function load() {
  const auth = await json("auth.php"); current = auth.profile; csrf = auth.csrf;
  const ids = ["montreal-evening", "montreal-dinner", "lac-solitaire", "ruisseau-bouchard", "cascades-falaises", "canoe-intro", "waber-falls", "shawinigan", "fjordtag-varianten"];
  const [rows, transfer20, transfer23, quebec, transfer29, orford, status] = await Promise.all([Promise.all(ids.map(id => json(`ideas.php?idea=${encodeURIComponent(id)}`))), json("transfer-vote-20-09.php"), json("transfer-vote.php"), json("04-quebec-city.php?api=1"), json("transfer-vote-29-09.php"), json("orford-activities-vote.php"), json("decision-status.php")]);
  fixedDecisions = status.decisions || {};
  const ideas = Object.fromEntries(ids.map((id, index) => [id, rows[index]]));
  const ratingChoice = id => both(ratings(ideas[id].ratings), choices(ideas[id].choices));
  const quebecIds = ["history", "nature", "citadelle", "foodtour", "night", "restaurant"];
  const quebecDone = people.filter(person => quebecIds.every(id => Number(quebec.ratings?.[id]?.[person] || 0) > 0 && Boolean(quebec.choices?.[id]?.[person])));
  const quebecLabels = { history: { individuell: "individuell", klassisch: "klassische Führung", figur: "Figurenführung" }, nature: { montmorency: "nur Montmorency", combo: "Montmorency + Île d’Orléans", island: "Île d’Orléans" }, citadelle: { citadelle: "Citadelle", plains: "Plains of Abraham", both: "Kombination" }, foodtour: { food: "Food Tour", histfood: "historische Food Tour", dinner: "keine Food Tour" }, night: { walk: "Nachtspaziergang", ferry: "Lévis-Fähre", ghost: "Ghost Tour" }, restaurant: { traditional: "traditionelle Québec-Küche", regional: "moderne regionale Küche", bistro: "Bistro / Brasserie", steak: "Steak & Seafood", fine: "Fine Dining", casual: "unkomplizierte lokale Küche" } };
  const quebecSuggestion = quebecIds.map(id => choiceFavorite(quebec.choices?.[id], quebecLabels[id])).join(" · ");
  decisions = [
    makeItem({ id: "montreal-evening", destination: "01 · Montréal", title: "Besonderer Abend", subtitle: "Grundsatz und Favorit aus vier Abendideen", href: "idea.php?id=montreal-evening", icon: "🌙", donePeople: ratingChoice("montreal-evening"), suggestion: choiceFavorite(ideas["montreal-evening"].choices, { aura: "AURA", twilight: "Twilight Walk", "night-tour": "Night Tour", "ghost-walk": "Ghost Walk" }) }),
    makeItem({ id: "montreal-dinner", destination: "01 · Montréal", title: "Dinner-Stil", subtitle: "Bedeutung und persönlicher Restaurantfavorit", href: "idea.php?id=montreal-dinner", icon: "🍽️", donePeople: ratingChoice("montreal-dinner"), suggestion: choiceFavorite(ideas["montreal-dinner"].choices, { "fine-dining": "Fine Dining", "quebec-cuisine": "moderne Québec-Küche", "steak-seafood": "Steak & Seafood", brasserie: "lebendige Brasserie", "montreal-classics": "typisch Montréal" }) }),
    makeItem({ id: "mauricie-hike", destination: "02 · Nature Nature", title: "Wanderung am Dienstag", subtitle: "Lac-Solitaire oder Ruisseau-Bouchard bewerten", href: "02-the-laurentians.php#ideas", icon: "🥾", donePeople: ideaRatings([ideas["lac-solitaire"], ideas["ruisseau-bouchard"]]), suggestion: ratingFavorite([{ label: "Lac-Solitaire", ratings: ideas["lac-solitaire"].ratings }, { label: "Ruisseau-Bouchard", ratings: ideas["ruisseau-bouchard"].ratings }]) }),
    makeItem({ id: "mauricie-flex", destination: "02 · Nature Nature", title: "Flexibler Mittwoch", subtitle: "Parkkombination, Kanu, Waber Falls oder Shawinigan", href: "02-the-laurentians.php#ideas", icon: "🛶", donePeople: ideaRatings([ideas["cascades-falaises"], ideas["canoe-intro"], ideas["waber-falls"], ideas.shawinigan]), suggestion: ratingFavorite([{ label: "Cascades & Falaises", ratings: ideas["cascades-falaises"].ratings }, { label: "Kanu-Einführung", ratings: ideas["canoe-intro"].ratings }, { label: "Waber Falls", ratings: ideas["waber-falls"].ratings }, { label: "Shawinigan", ratings: ideas.shawinigan.ratings }]) }),
    makeItem({ id: "transfer-20", destination: "02 · Transfer", title: "Montréal → Nature Nature", subtitle: "Direkt, Pointe-du-Lac oder Trois-Rivières", href: "02-transfer-20-09.php", icon: "🚙", donePeople: variants(transfer20, ["a", "b", "c"]), suggestion: ratingFavorite([{ label: "A · direkt & entspannt", ratings: transfer20.variants?.a?.ratings }, { label: "B · Pointe-du-Lac", ratings: transfer20.variants?.b?.ratings }, { label: "C · Trois-Rivières", ratings: transfer20.variants?.c?.ratings }]) }),
    makeItem({ id: "transfer-23", destination: "03 · Transfer", title: "Nature Nature → Sainte-Rose", subtitle: "Roadtrip-Stopps oder Val-Jalbert", href: "03-transfer-23-09.php", icon: "🗺️", donePeople: variants(transfer23, ["b2", "c"]), suggestion: ratingFavorite([{ label: "B2 · flexible Roadtrip-Stopps", ratings: transfer23.variants?.b2?.ratings }, { label: "C · Val-Jalbert", ratings: transfer23.variants?.c?.ratings }]) }),
    makeItem({ id: "fjord-day", destination: "03 · Sainte-Rose", title: "Fjordtag", subtitle: "Seekajak, Schiff, Elektro-Side-by-Side oder Regenplan", href: "idea.php?id=fjordtag-varianten", icon: "🌊", donePeople: ratingChoice("fjordtag-varianten"), suggestion: choiceFavorite(ideas["fjordtag-varianten"].choices, { kayak: "A · Seekajak", majestueuse: "B · La Majestueuse", "side-by-side": "C · Elektro-Side-by-Side", rain: "D · Regenplan" }) }),
    makeItem({ id: "quebec-day", destination: "04 · Québec City", title: "Der volle Québec-Tag", subtitle: "Sechs Grundsatz- und Variantenentscheidungen", href: "04-quebec-city.php#entscheidungen", icon: "⚜️", donePeople: quebecDone, suggestion: quebecSuggestion }),
    makeItem({ id: "transfer-29", destination: "05 · Transfer", title: "Québec City → Orford", subtitle: "Direkt, Genussstopp oder Parc Marie-Victorin", href: "05-transfer-29-09.php", icon: "🚗", donePeople: variants(transfer29, ["a", "b", "c"]), suggestion: ratingFavorite([{ label: "A · direkt", ratings: transfer29.variants?.a?.ratings }, { label: "B · Genussstopp", ratings: transfer29.variants?.b?.ratings }, { label: "C · Parc Marie-Victorin", ratings: transfer29.variants?.c?.ratings }]) }),
    makeItem({ id: "orford-days", destination: "05 · Orford", title: "Zwei Tage in Orford", subtitle: "Die zwei stärksten Bausteine für die Tagesprogramme", href: "05-aktivitaeten.php#abstimmung", icon: "🍁", donePeople: variants(orford, ["hike", "park", "magog", "abbey", "cruise", "spa"]), suggestion: ratingFavorite([{ label: "Mont-Orford-Wanderung", ratings: orford.variants?.hike?.ratings }, { label: "Nationalpark", ratings: orford.variants?.park?.ratings }, { label: "Magog", ratings: orford.variants?.magog?.ratings }, { label: "Abbaye Saint-Benoît", ratings: orford.variants?.abbey?.ratings }, { label: "Schifffahrt", ratings: orford.variants?.cruise?.ratings }, { label: "Spa", ratings: orford.variants?.spa?.ratings }], 2) }),
    { id: "whale", destination: "04 · Tadoussac", title: "Walbeobachtung per Schiff", subtitle: "Bereits gebucht · Details vor der Reise nochmals prüfen", href: "04-quebec-city.php#montag", icon: "🐋", donePeople: people, complete: true, mineDone: true, booked: true, suggestion: "Walbeobachtung per Schiff" },
  ];
  applyStates(); render();
}

function decisionBox(decision) {
  if (decision.state === "booked") return `<div class="dashboard-decision booked"><small>Gebucht</small><strong>${esc(decision.suggestion)}</strong></div>`;
  if (decision.fixed) { const setter = names[decision.fixed.setBy] || "euch", changed = decision.fixed.summary !== decision.suggestion; return `<div class="dashboard-decision fixed ${changed ? "changed" : ""}"><small>${changed ? "Neue Stimmen haben den Trend verändert" : "Vorläufig festgelegt"}</small><strong>${esc(decision.fixed.summary)}</strong><span>von ${esc(setter)} · jederzeit änderbar</span><button type="button" data-reopen="${esc(decision.id)}">Wieder öffnen</button></div>`; }
  return `<div class="dashboard-decision ${decision.complete ? "ready" : "trend"}"><small>${decision.complete ? "Aktueller Favorit" : "Aktueller Zwischenstand"}</small><strong>${esc(decision.suggestion)}</strong>${decision.complete ? `<button type="button" data-finalize="${esc(decision.id)}">Vorläufig festlegen</button>` : `<span>Festlegen ist möglich, sobald alle vier abgestimmt haben.</span>`}</div>`;
}
function render() {
  const action = decisions.filter(decision => decision.state !== "booked"), done = action.filter(decision => decision.mineDone).length, open = action.length - done, percent = Math.round(done / action.length * 100);
  document.querySelector("#dashboard-percent").textContent = `${percent} %`; document.querySelector("#dashboard-progress-bar").style.width = `${percent}%`; document.querySelector("#dashboard-personal-copy").textContent = open ? `Dir fehlen noch ${open} von ${action.length} Entscheidungen.` : "Du hast alle aktuellen Entscheidungen bearbeitet.";
  document.querySelector("#dashboard-roster").innerHTML = people.map(person => { const count = action.filter(decision => decision.donePeople.includes(person)).length; return `<div class="dashboard-person"><i class="avatar ${avatars[person]}"></i><span><strong>${names[person]}</strong><small>${count}/${action.length} erledigt</small></span></div>`; }).join("");
  const visible = decisions.filter(decision => filter === "mine" ? decision.state === "open" && !decision.mineDone : filter === decision.state); document.querySelector("#dashboard-status").hidden = true;
  document.querySelector("#dashboard-list").innerHTML = visible.length ? visible.map(decision => { const missing = people.filter(person => !decision.donePeople.includes(person)); const roster = people.map(person => `<span class="dashboard-mini-person ${decision.donePeople.includes(person) ? "ready" : "missing"}" title="${esc(names[person])}"><i class="avatar ${avatars[person]}"></i><b>${decision.donePeople.includes(person) ? "✓" : "·"}</b></span>`).join(""); const label = decision.state === "booked" ? "Details ansehen" : decision.mineDone ? "Abstimmung ansehen" : "Jetzt abstimmen"; return `<article class="dashboard-card ${decision.state}"><div class="dashboard-card-icon">${decision.icon}</div><div class="dashboard-card-main"><p class="eyebrow">${esc(decision.destination)}</p><h2>${esc(decision.title)}</h2><p>${esc(decision.subtitle)}</p><div class="dashboard-card-foot"><div class="dashboard-mini-roster">${roster}</div><small>${decision.state === "booked" ? "Fest eingeplant" : decision.complete ? "Alle vier haben abgestimmt" : `${missing.length} ${missing.length === 1 ? "Person" : "Personen"} noch unvollständig`}</small></div>${decisionBox(decision)}</div><a href="${esc(decision.href)}">${label} →</a></article>`; }).join("") : `<div class="dashboard-empty"><span>✓</span><h2>Hier ist gerade nichts offen.</h2><p>Wechsle den Filter oder genieße kurz das gute Gefühl.</p></div>`;
}

document.querySelector(".dashboard-filters").addEventListener("click", event => { const button = event.target.closest("[data-dashboard-filter]"); if (!button) return; filter = button.dataset.dashboardFilter; document.querySelectorAll("[data-dashboard-filter]").forEach(item => item.classList.toggle("active", item === button)); render(); });
document.querySelector("#dashboard-new-idea").addEventListener("change", event => { if (event.target.value) window.location.href = `new-idea.php?destination=${encodeURIComponent(event.target.value)}`; });
document.querySelector("#dashboard-list").addEventListener("click", async event => { const finalize = event.target.closest("[data-finalize]"), reopen = event.target.closest("[data-reopen]"); if (!finalize && !reopen) return; const id = (finalize || reopen).dataset.finalize || (finalize || reopen).dataset.reopen, decision = decisions.find(item => item.id === id); if (!decision) return; const message = finalize ? `„${decision.suggestion}“ vorläufig festlegen? Die Entscheidung kann später wieder geöffnet werden.` : "Diese vorläufige Entscheidung wieder öffnen?"; if (!window.confirm(message)) return; try { await saveDecision(finalize ? { action: "set", decision: id, summary: decision.suggestion } : { action: "reopen", decision: id }); } catch (error) { window.alert(error.message); } });
load().catch(error => { document.querySelector("#dashboard-status").innerHTML = `<div class="dashboard-error">${esc(error.message)} Bitte lade die Seite erneut.</div>`; });
