const people=["lars","andrea","christina","manfred"],names={lars:"Lars",andrea:"Andrea",christina:"Christina",manfred:"Manfred"},avatars={lars:"avatar-lars",andrea:"avatar-andrea",christina:"avatar-christina",manfred:"avatar-manfred"};let current="",filter="mine",decisions=[];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function json(url){const r=await fetch(`${url}${url.includes("?")?"&":"?"}t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error("Ein Teil der Abstimmungen konnte nicht geladen werden.");return r.json()}
const ratings=r=>people.filter(p=>Number(r?.[p]||0)>0),choices=c=>people.filter(p=>Boolean(c?.[p])),both=(...groups)=>people.filter(p=>groups.every(g=>g.includes(p))),variants=(data,ids)=>people.filter(p=>ids.every(id=>Number(data?.variants?.[id]?.ratings?.[p]||0)>0)),ideaRatings=rows=>people.filter(p=>rows.every(row=>Number(row?.ratings?.[p]||0)>0));
function item(data){const complete=data.donePeople.length===4;return{...data,complete,mineDone:data.donePeople.includes(current),state:complete?"done":"open"}}
async function load(){const auth=await json("auth.php");current=auth.profile;const ids=["montreal-evening","montreal-dinner","lac-solitaire","ruisseau-bouchard","cascades-falaises","canoe-intro","waber-falls","shawinigan","fjordtag-varianten"];const [rows,t20,t23,q,t29,o]=await Promise.all([Promise.all(ids.map(id=>json(`ideas.php?idea=${encodeURIComponent(id)}`))),json("transfer-vote-20-09.php"),json("transfer-vote.php"),json("04-quebec-city.php?api=1"),json("transfer-vote-29-09.php"),json("orford-activities-vote.php")]);const ideas=Object.fromEntries(ids.map((id,i)=>[id,rows[i]])),ratingChoice=id=>both(ratings(ideas[id].ratings),choices(ideas[id].choices)),qids=["history","nature","citadelle","foodtour","night","restaurant"],qdone=people.filter(p=>qids.every(id=>Number(q.ratings?.[id]?.[p]||0)>0&&Boolean(q.choices?.[id]?.[p])));
decisions=[
item({destination:"01 · Montréal",title:"Besonderer Abend",subtitle:"Grundsatz und Favorit aus vier Abendideen",href:"idea.php?id=montreal-evening",icon:"🌙",donePeople:ratingChoice("montreal-evening")}),
item({destination:"01 · Montréal",title:"Dinner-Stil",subtitle:"Bedeutung und persönlicher Restaurantfavorit",href:"idea.php?id=montreal-dinner",icon:"🍽️",donePeople:ratingChoice("montreal-dinner")}),
item({destination:"02 · Nature Nature",title:"Wanderung am Dienstag",subtitle:"Lac-Solitaire oder Ruisseau-Bouchard bewerten",href:"02-the-laurentians.php#ideas",icon:"🥾",donePeople:ideaRatings([ideas["lac-solitaire"],ideas["ruisseau-bouchard"]])}),
item({destination:"02 · Nature Nature",title:"Flexibler Mittwoch",subtitle:"Parkkombination, Kanu, Waber Falls oder Shawinigan",href:"02-the-laurentians.php#ideas",icon:"🛶",donePeople:ideaRatings([ideas["cascades-falaises"],ideas["canoe-intro"],ideas["waber-falls"],ideas.shawinigan])}),
item({destination:"02 · Transfer",title:"Montréal → Nature Nature",subtitle:"Direkt, Pointe-du-Lac oder Trois-Rivières",href:"02-transfer-20-09.php",icon:"🚙",donePeople:variants(t20,["a","b","c"])}),
item({destination:"03 · Transfer",title:"Nature Nature → Sainte-Rose",subtitle:"Roadtrip-Stopps oder Val-Jalbert",href:"03-transfer-23-09.php",icon:"🗺️",donePeople:variants(t23,["b2","c"])}),
item({destination:"03 · Sainte-Rose",title:"Fjordtag",subtitle:"Seekajak, Schiff, Elektro-Side-by-Side oder Regenplan",href:"idea.php?id=fjordtag-varianten",icon:"🌊",donePeople:ratingChoice("fjordtag-varianten")}),
item({destination:"04 · Québec City",title:"Der volle Québec-Tag",subtitle:"Sechs Grundsatz- und Variantenentscheidungen",href:"04-quebec-city.php#entscheidungen",icon:"⚜️",donePeople:qdone}),
item({destination:"05 · Transfer",title:"Québec City → Orford",subtitle:"Direkt, Genussstopp oder Parc Marie-Victorin",href:"05-transfer-29-09.php",icon:"🚗",donePeople:variants(t29,["a","b","c"])}),
item({destination:"05 · Orford",title:"Zwei Tage in Orford",subtitle:"Sechs Bausteine für die beiden Tagesprogramme",href:"05-aktivitaeten.php#abstimmung",icon:"🍁",donePeople:variants(o,["hike","park","magog","abbey","cruise","spa"])}),
{destination:"04 · Tadoussac",title:"Walbeobachtung per Schiff",subtitle:"Bereits gebucht · Details vor der Reise nochmals prüfen",href:"04-quebec-city.php#montag",icon:"🐋",donePeople:people,complete:true,mineDone:true,state:"booked"}
];render()}
function render(){const action=decisions.filter(x=>x.state!=="booked"),done=action.filter(x=>x.mineDone).length,open=action.length-done,percent=Math.round(done/action.length*100);document.querySelector("#dashboard-percent").textContent=`${percent} %`;document.querySelector("#dashboard-progress-bar").style.width=`${percent}%`;document.querySelector("#dashboard-personal-copy").textContent=open?`Dir fehlen noch ${open} von ${action.length} Entscheidungen.`:"Du hast alle aktuellen Entscheidungen bearbeitet.";document.querySelector("#dashboard-roster").innerHTML=people.map(p=>{const count=action.filter(x=>x.donePeople.includes(p)).length;return`<div class="dashboard-person"><i class="avatar ${avatars[p]}"></i><span><strong>${names[p]}</strong><small>${count}/${action.length} erledigt</small></span></div>`}).join("");const visible=decisions.filter(x=>filter==="mine"?x.state==="open"&&!x.mineDone:filter==="open"?x.state==="open":filter==="done"?x.state==="done":x.state==="booked");document.querySelector("#dashboard-status").hidden=true;document.querySelector("#dashboard-list").innerHTML=visible.length?visible.map(x=>{const missing=people.filter(p=>!x.donePeople.includes(p)),roster=people.map(p=>`<span class="dashboard-mini-person ${x.donePeople.includes(p)?"ready":"missing"}" title="${esc(names[p])}"><i class="avatar ${avatars[p]}"></i><b>${x.donePeople.includes(p)?"✓":"·"}</b></span>`).join(""),label=x.state==="booked"?"Details ansehen":x.mineDone?"Zwischenstand ansehen":"Jetzt abstimmen";return`<article class="dashboard-card ${x.state}"><div class="dashboard-card-icon">${x.icon}</div><div class="dashboard-card-main"><p class="eyebrow">${esc(x.destination)}</p><h2>${esc(x.title)}</h2><p>${esc(x.subtitle)}</p><div class="dashboard-card-foot"><div class="dashboard-mini-roster">${roster}</div><small>${x.state==="booked"?"Fest eingeplant":x.complete?"Alle vier fertig":`${missing.length} ${missing.length===1?"Person":"Personen"} noch unvollständig`}</small></div></div><a href="${esc(x.href)}">${label} →</a></article>`}).join(""):`<div class="dashboard-empty"><span>✓</span><h2>Hier ist gerade nichts offen.</h2><p>Wechsle den Filter oder genieße kurz das gute Gefühl.</p></div>`}
document.querySelector(".dashboard-filters").addEventListener("click",e=>{const b=e.target.closest("[data-dashboard-filter]");if(!b)return;filter=b.dataset.dashboardFilter;document.querySelectorAll("[data-dashboard-filter]").forEach(x=>x.classList.toggle("active",x===b));render()});load().catch(e=>{document.querySelector("#dashboard-status").innerHTML=`<div class="dashboard-error">${esc(e.message)} Bitte lade die Seite erneut.</div>`});
