<?php
declare(strict_types=1);
require __DIR__ . '/auth-lib.php';
canada_require_login();
$profileId = canada_profile();
$profile = CANADA_PROFILES[$profileId];
$destination = $destination ?? 'montreal';
?>
<!doctype html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#143b2b"><meta name="description" content="Canada 2027 – Reiseplanung"><meta name="robots" content="noindex,nofollow"><title>Canada 2027</title><link rel="stylesheet" href="styles.css"></head><body class="destination-page" data-destination="<?= htmlspecialchars($destination, ENT_QUOTES) ?>">
<header class="topbar"><a class="brand" href="index.php"><span class="brand-mark">🍁</span><span><strong>Canada 2027</strong><small>17. September – 2. Oktober</small></span></a><nav class="desktop-nav"><a href="index.php">Übersicht</a><a class="active" href="#ideas">Ideen</a></nav><a class="profile-chip" href="login.php?switch=1&amp;next=<?= rawurlencode($_SERVER['REQUEST_URI'] ?? '/index.php') ?>" aria-label="Profil wechseln"><i class="avatar <?= $profile['avatar'] ?>"></i><span><?= $profile['name'] ?></span></a></header>
<main id="top"><section class="destination-hero"><a class="back-link" href="index.php">← Reiseübersicht</a><p class="eyebrow">Destination</p><h1 id="destination-title"></h1><p id="destination-summary"></p></section><nav class="destination-tabs destination-switcher" id="destination-tabs" role="tablist" aria-label="Destination auswählen"></nav>
<section class="section"><div class="section-head"><div><p class="eyebrow">Vom Ankommen bis zur Abreise</p><h2>Anreise &amp; Tage vor Ort</h2></div><div class="legend"><span><i class="dot move"></i> Reisetag</span><span><i class="dot stay"></i> Tag vor Ort</span></div></div><div class="route-list" id="route-list"></div></section>
<section class="section ideas" id="ideas"><div class="section-head ideas-head"><div><p class="eyebrow">Gemeinsam entscheiden</p><h2 id="ideas-title"></h2></div><div class="filters"><button class="filter active" data-filter="all">Alle</button><button class="filter" data-filter="booked">Gebucht</button><button class="filter" data-filter="idea">Ideen</button></div></div><a id="comparison-link" class="comparison-link" href="file.php?name=00_Vergleich_Aktivitaeten_Mauricie.pdf" target="_blank">PDF · Vergleich aller Aktivitäten ↗</a><div class="idea-grid" id="idea-grid"></div></section></main>
<nav class="mobile-nav"><a href="index.php"><span>⌁</span>Reise</a><a class="active" href="#ideas"><span>★</span>Ideen</a><a href="index.php#travellers"><span>♙</span>Wir vier</a></nav><dialog id="details-dialog"><button class="close-dialog" aria-label="Schließen">×</button><div id="dialog-content"></div></dialog><script src="app.js?v=20260905-3"></script></body></html>
